/*
Task 2

Design the child class Striker and Defender that inherits from the Football class so that the given output matches with the output generated by the driver code.

Parent Class 
public class Football {
  public String name;
  public int age;
  public int stamina;
  
  public Football(String name, int age, int stamina) {
    this.name = name;
    this.age = age;
    this.stamina = stamina;
  }
  
  public void display() {
    System.out.println("Name: " + name);
    System.out.println("Age: " + age);
    System.out.println("Stamina: " + stamina);
  }
  
  public void calculatePerformance() {
    System.out.println("Performance is not defined yet");
  }
}

Driver Code
public class FootballTester {
  public static void main(String[] args) {
    Striker ronaldo = new Striker("Ronaldo", 39, 90, 901, 1000);
    Defender ramos = new Defender("Ramos", 38, 85, 1000, 100);
    
    System.out.println("1========");
    ronaldo.display();
    System.out.println("2========");
    ronaldo.calculatePerformance();
    System.out.println("3========");
    ramos.display();
    System.out.println("4========");
    ramos.calculatePerformance();
  }
}

Output
1========
Name: Ronaldo
Age: 39
Stamina: 90
Goals: 901
Shots on target: 1000
2========
Performance: 0.901
3========
Name: Ramos
Age: 38
Stamina: 85
Tackles: 1000
Interceptions: 100
4========
Performance: 0.1
*/

public class FootballTester {
    public static void main(String[] args) {
        Striker ronaldo = new Striker("Ronaldo", 39, 90, 901, 1000);
        Defender ramos = new Defender("Ramos", 38, 85, 1000, 100);

        System.out.println("1========");
        ronaldo.display();
        System.out.println("2========");
        ronaldo.calculatePerformance();
        System.out.println("3========");
        ramos.display();
        System.out.println("4========");
        ramos.calculatePerformance();
    }
}